import Head from 'next/head';
import {BsFillMoonStarsFill , BsGithub} from "react-icons/bs";
import {AiFillTwitterCircle, AiFillLinkedin} from "react-icons/ai";
import Image from "next/image";
import deved  from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import weather from "../public/weather.png";
import recipe from "../public/recipe.png";
import indeedScraper from "../public/indeedScraper.png";
import consulting  from "../public/consulting.png";
import shoppingcart  from "../public/shoppingcart.png"  
import {useState } from "react";
import { NavLink } from 'react-router-dom';

export default function Home() {

  const [darkMode , setDarkMode ] = useState(true);
  return (
    <div className={darkMode?"dark":" "}>
      <Head>
        <title>React Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="">
         <nav className="py-5 mb-5 flex justify-between">
          <h1 className="text-2xl font-burtons dark:text-white"> developed by Jay</h1>
          <ul className="flex items-center">
            <li className="dark:text-white"><BsFillMoonStarsFill onClick={()=>setDarkMode(!darkMode)}  className="cursor-pointer text-2xl" /></li>
            <li>
              <a className=" bg-gradient-to-r from-cyan-500 to-teal-500  text-white px-4 py-2 rounded-md ml-8"  href="#">Resume</a>
              </li>
          </ul>
        </nav>
        <div className=" text-center p-10 pt-2 ">
          <h2 className=" text-5xl py-2 text-teal-600 font-medium md:text-6xl ">Jay Singh</h2>
          <h3 className=" text-2xl py-2 md:text-3xl dark:text-white">Front End Developer </h3>
        </div>
        <div className=" text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
        <a href="https://github.com/Jay5780" target="_blank"><BsGithub/></a>
          <a href="https://www.linkedin.com/in/jay-singh-99538b22a" target="_blank"><AiFillLinkedin/></a> 
        </div>
        <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 overflow-hidden md:h-96 md:w-96">
        <Image src={deved} layout="fill" objectFit="cover" />
        </div>
        </section>
        <section>
          <div className="flex justify-center bg-slate-400 mt-8 rounded-md w-15 ">
            <h3 className="text-xl md:text-4xl font-bold pt-4 py-4 dark:text-black">Projects </h3>
          </div>
          <div className="  justify-center gap-10">
            <div className="text-center justify-center  shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <a href="https://jay5780.github.io/Recipe_App/" target="_blank" >
              <Image className="mx-auto mb-3 rounded-lg" src={recipe}  />
              <h3 className="  md:text-3xl  font-bold pt-4 pb-2">Recipe App : deliciouss</h3>
              </a>
              <p className="text-gray-1100 py-1  md:text-lg font-medium">User can search for ingridients and process to make
               a dish ... </p>
              <h4 className=" md:text-2xl py-4 font-semibold text-teal-600">Technologies used</h4>
              <div className='flex justify-center gap-3 md:gap-10'>
              <p className="text-gray-800 py-1  md:text-lg font-medium">React JS</p>
              <p className="text-gray-800 py-1 md:text-lg font-medium">Javascript</p>
              <p className="text-gray-800 py-1 md:text-lg font-medium">Tailwind CSS</p>
              <p className="text-gray-800 py-1 md:text-lg font-medium">HTML</p>
              <p className="text-gray-800 py-1 md:text-lg font-medium">API : spoonacular</p>
              <a href="https://github.com/Jay5780/Recipe_App"  target="_blank" ><BsGithub className=' md:text-3xl'/></a>
              </div>
            </div>
             
            <div className="text-center justify-center  shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <a href="https://jay5780.github.io/Shopping_Cart/" target="_blank" >
              <Image className="mx-auto mb-3 rounded-lg" src={shoppingcart}  />
              <h3 className="  md:text-3xl  font-bold pt-4 pb-2">Shopping Cart </h3>
              </a>
              <p className="text-gray-1100 py-1  md:text-lg font-medium">User can add products to cart and remove from it . </p>
              <h4 className=" md:text-2xl py-4 font-semibold text-teal-600">Technologies used</h4>
              <div className='flex justify-center gap-3 md:gap-10'>
              <p className="text-gray-800 py-1 md:text-lg font-medium">React Js</p>
              <p className="text-gray-800 py-1 md:text-lg font-medium">Redux Toolkit</p>
              <p className="text-gray-800 py-1 md:text-lg font-medium">TypeScript</p>
              <p className="text-gray-800 py-1 md:text-lg font-medium">BootStrap</p>
              <a href="https://github.com/Jay5780/Shopping_Cart"  target="_blank" ><BsGithub className=' md:text-3xl'/></a>
              </div>
            </div>

            <div className="text-center justify-center  shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <a href="https://jay5780.github.io/RealTime_WeatherAPP.github.io/" target="_blank" >
              <Image className="mx-auto mb-3 rounded-lg" src={weather}  />
              <h3 className="  md:text-3xl  font-bold pt-4 pb-2">Real Time Weather App</h3>
              </a>
              <p className="text-gray-1100 py-1  md:text-lg font-medium">User can search real time weather conditions of any city . </p>
              <h4 className=" md:text-2xl py-4 font-semibold text-teal-600">Technologies used</h4>
              <div className='flex justify-center gap-3 md:gap-10'>
              <p className="text-gray-800 py-1 md:text-lg font-medium">Javascript</p>
              <p className="text-gray-800 py-1 md:text-lg font-medium">HTML</p>
              <p className="text-gray-800 py-1 md:text-lg font-medium">CSS</p>
              <p className="text-gray-800 py-1 md:text-lg font-medium">API : openweathermap</p>
              <a href="https://github.com/Jay5780/RealTime_WeatherAPP.github.io"  target="_blank" ><BsGithub className=' md:text-3xl'/></a>
              </div>
            </div>
             
            <div className="text-center justify-center  shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <a href="https://jay5780.github.io/RealTime_WeatherAPP.github.io/" target="_blank" >
              <Image className="mx-auto mb-3 rounded-lg" src={indeedScraper}  />
              <h3 className="  md:text-3xl  font-bold pt-4 pb-2">Indeed Job Scraper</h3>
              </a>
              <p className="text-gray-1100 py-1  md:text-lg font-medium">Program scrapes a particular job title from given number of pages. </p>
              <h4 className=" md:text-2xl py-4 font-semibold text-teal-600">Technologies used</h4>
              <div className='flex justify-center gap-3 md:gap-10'>
              <p className="text-gray-800 py-1 md:text-lg font-medium">Python</p>
              <p className="text-gray-800 py-1 md:text-lg font-medium">Selenium</p>
              <a href="https://github.com/Jay5780/Indeed_Job_Scraper"  target="_blank" ><BsGithub className=' md:text-3xl'/></a>
              </div>
            </div>




          </div>
        </section>
        <section>
          <div className="pb-5  bg-black px-0 mx-0 dark:bg-white rounded-md">
            <h3 className="text-3xl py-2 px-5 font-semibold text-white  dark:text-black">Skills</h3>
            <div className="flex flex-wrap gap-6">
            <p className="text-white py-1 px-5 dark:text-black">React JS</p>
            <p className="text-white py-1 px-5 dark:text-black">Javascript</p>
            <p className="text-white py-1 px-5 dark:text-black">TypeScript</p>
            <p className="text-white py-1 px-5 dark:text-black ">Tailwind CSS</p>
            <p className="text-white py-1 px-5 dark:text-black">BootStrap</p>
            <p className="text-white py-1 px-5 dark:text-black ">HTML</p>
            <p className="text-white py-1 px-5 dark:text-black ">Python</p>
            <p className="text-white py-1 px-5 dark:text-black ">Selenium</p> 
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
